# Regressão Linear Versão Matricial
## TODO:
- Melhorar o nomeamento
- Comentar o código
- Adicionar type hints
- Adicionar docstrings
- Explicar a matemática


## Docstring example 

``` python
def complex(real=0.0, imag=0.0):
    """Form a complex number.

    Keyword arguments:
    real -- the real part (default 0.0)
    imag -- the imaginary part (default 0.0)
    """
    if imag == 0.0 and real == 0.0:
        return complex_zero
    ...

```

In [3]:
import numpy as np

In [4]:
data = np.asarray(((0, 0), (0, 1), (1, 0), (1, 1)))
data_b = np.c_[np.ones((4, 1)), data] # Adciona a0 às entradas
data_b

array([[1., 0., 0.],
       [1., 0., 1.],
       [1., 1., 0.],
       [1., 1., 1.]])

É necessário adicionar $x_0 = 1$ nos vetores de caractéristicas. É a forma de adicionar o parâmetro de viés no cálculo. Essa operação é realizada pela seguinte linha de código:

``` python

data_b = np.c_[np.ones((4, 1)), data]

```
A matriz data tem ordem 4x2, np.c_ retorna uma combinação de uma matriz de ordem 4x1 de elementos 1 e data.

In [5]:
y = np.asarray((0, 0, 0, 1))
y

array([0, 0, 0, 1])

y é o vetor das saídas reais. Como estamos tratando do caso do AND lógico, apenas no caso das entradas serem (1, 1) a saída real é 0. 

In [6]:
theta = np.linalg.inv((np.dot(data_b.T, data_b))).dot(data_b.T).dot(y)
theta = theta.reshape(1, 3)
theta

array([[-0.25,  0.5 ,  0.5 ]])

theta é o vetor de parâmetros. A equação para descobrir os parâmetros da regressão linear é a seguinte:
$$\theta = (X^TX)^{-1}X^TY$$ 

In [7]:
t = np.asarray([[1, 1]])
t_b = np.c_[np.ones(1), t]
t_b

array([[1., 1., 1.]])

In [8]:
theta.dot(t_b.T)

array([[0.75]])

In [9]:
from sklearn.linear_model import LinearRegression
lin_reg = LinearRegression()
lin_reg.fit(data, y)
lin_reg.intercept_, lin_reg.coef_

(-0.25, array([0.5, 0.5]))

A nossa regressão linear encontrou os mesmos parâmetros que a regressão linear da biblioteca Scikit Learn. Isso significa que nós fomos muito bem :).

In [48]:
lin_reg.predict(t)

array([0.75])