# Regressão Linear Versão Matricial

In [1]:
import numpy as np

In [23]:
data = np.asarray(((0, 0), (0, 1), (1, 0), (1, 1)))
data_b = np.c_[np.ones((4, 1)), data] # Adciona a0 às entradas
data_b

array([[1., 0., 0.],
       [1., 0., 1.],
       [1., 1., 0.],
       [1., 1., 1.]])

In [18]:
y = np.asarray((0, 0, 0, 1))
y

array([0, 0, 0, 1])

In [44]:
theta = np.linalg.inv((np.dot(data_b.T, data_b))).dot(data_b.T).dot(y)
theta = theta.reshape(1, 3)
theta.shape

(1, 3)

In [43]:
t = np.asarray([[1, 1]])
t_b = np.c_[np.ones(1), t]
t_b

array([[1., 1., 1.]])

In [45]:
theta.dot(t_b.T)

array([[0.75]])

In [47]:
from sklearn.linear_model import LinearRegression
lin_reg = LinearRegression()
lin_reg.fit(data, y)
lin_reg.intercept_, lin_reg.coef_

(-0.25, array([0.5, 0.5]))

In [48]:
lin_reg.predict(t)

array([0.75])

Muito orgulho :)