#  Neurônio MCP
## TODO:
- Melhorar o nomeamento
- Comentar o código
- Adicionar type hints
- Adicionar docstrings
- Adicionar explicar a matemática
- Adicionar blocos Markdown para os casos AND e OR

## Docstring example 

``` python
def complex(real=0.0, imag=0.0):
    """Form a complex number.

    Keyword arguments:
    real -- the real part (default 0.0)
    imag -- the imaginary part (default 0.0)
    """
    if imag == 0.0 and real == 0.0:
        return complex_zero
    ...

```

In [3]:
import numpy as np
import numpy.typing as npt

In [4]:
def MCP(X: npt.ArrayLike, w: npt.ArrayLike, theta: float) -> npt.ArrayLike:
    """Return a numpy array with the predictions from the MCP neuron.

    Keyword arguments:
    X -- a matrix containing the feature vectors 
    w -- the parameters vector
    theta -- the threshold for the MCP
    """
    
    w = np.c_[np.zeros(w.shape[0]) + theta, w]
    return np.where(w.dot(X.T) <= 0, 0, 1)

In [5]:
theta = 1.0
w =  np.array([[-0.5, -0.6]])
X = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
X = np.c_[np.zeros(X.shape[0]).T + 1, X]
X

array([[1., 0., 0.],
       [1., 0., 1.],
       [1., 1., 0.],
       [1., 1., 1.]])

In [6]:
MCP(X, w, theta)

array([[1, 1, 1, 0]])

In [9]:
from MCP import MCP
perceptron = MCP()
X = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
perceptron.fit(X)

[[1. 0. 0.]
 [1. 0. 1.]
 [1. 1. 0.]
 [1. 1. 1.]]
